### ISSUE TITLE
Does this handle unicode in paths?

### ISSUE THREAD

**Issue by hefvandz** [mrsilver76/itunes_playlist_exporter#16]
Nice work here! stoked to try it out tonight. 

Are you still putting time into it?
One of my main frustrations after making the leap from Itunes to Plexamp has been the issue described here https://forums.plex.tv/t/itunes-import-fails-due-to-unicode-in-paths/811937

I have a lot of music from artists outside of North America. lots of weird accents, or non-english characters used in album artist and album names. Means the itunes plugin craps out when I try and import my playlists and ratings. Lots of stuff missing from playlists, lots of ratings that don't get moved over.

**Comment by mrsilver76** [comment]
Hey! Fingers crossed it works for you. I'm still maintaining the code, but my plans to rewrite the whole thing in C# (and use ini files for the configuration) has been put on hold due to a lack of time and the chance that the new iTunes app doesn't actually support the COM SDK.

Regarding your questions:

- Playlists are written out as UTF-8
- The filename for the playlist has all accents removed (so "café" becomes "cafe") and any "problematic" characters removed.
- The proper title of the playlist is added to the playlist using the `#playlist:` header
- When the script attempts to load the playlist, if the title in `#playlist:` doesn't match the filename then it makes a copy of the playlist with a temporary name, uploads that playlist to Plex and then uses the Plex API to find that temporary name and rename the playlist to the correct name.

Give it a go, let me know how you get on and I'll try and see if I can help you.
