### ISSUE TITLE
500 Internal Server Error when adding playlist

### ISSUE THREAD

**Issue by Babaloued** [mrsilver76/itunes_playlist_exporter#18]
Hi,

Everything works fine until the script try to upload the playlist on PLEX
My playlist, on my PC, is correctly recreated on my NAS where all my music is stored. The script delete all existing playlists on my plex but them, I have an error 500 when it tries to upload playlists

![image](https://github.com/user-attachments/assets/c27b6d4f-c258-4f4e-b238-ff33b4d63823)

Here's the error on my plex 
![image](https://github.com/user-attachments/assets/a246de60-1aaf-4277-851b-161d459451b0)

Playlist created by the script 
![image](https://github.com/user-attachments/assets/b6e5ea7f-986e-47c6-a03c-4639e57ef394)

NAS folder is accessible from my PLEX server
![image](https://github.com/user-attachments/assets/2ee68e42-f6aa-49d7-8895-5f1a3ccfd311)

PLEX version : 4.137.1

Script is launched from my PC, PLEX is on a different server (192.168.1.17) and all data are on NAS

Any help would be appreciated

Regards

**Comment by mrsilver76** [comment]
Sorry for the delay in responding. You'll notice that Plex isn't astoundingly helpful with error messages when it comes to trying to work out why a playlist didn't work!

Can you try removing everything from your `m3u` apart from the first four lines (basically the first track) and try running the `curl` command manually on that?

If that doesn't work then we've nailed down the issue to the path of the file. If that does work then I suspect the problem is the Chinese letters.

**Comment by Babaloued** [comment]
No worries

Soooooo, for no reason, it works perfectly now and I managed to import playlist with all songs inside... I changed nothing, no update of plex, itunes or PC. Magic...

nb: for the error 500 it was my fault. Music path was incorrect on my NAS but for the second playlist which was not imported with no error, just works fine now
